### ISSUE TITLE
Empty cache file throws error

### ISSUE THREAD

**Issue by cosmincmihai** [arifhp86/laravel-clear-expired-cache-file#11]
If for some reason, a cache file end with 0 size, the following error is thrown:

 TypeError

  Arifhp86\ClearExpiredCacheFile\CacheGarbageCollector::getExpireDate(): Return value must be of type int, string returned

  at vendor/arifhp86/laravel-clear-expired-cache-file/src/CacheGarbageCollector.php:159
    155▕         $expire = fread($handle, 10);
    156▕         fclose($handle);
    157▕         \Log::info($file . ' ' . $expire);
    158▕
  ➜ 159▕         return $expire;
    160▕     }
    161▕
    162▕     protected function notACacheFile(string $name): bool
    163▕     {

      +16 vendor frames

  17  artisan:35
  
  A simple fix is to enforce the returned value of getExpireDate method to int.
![Screenshot 2024-08-19 at 7 32 24 PM](https://github.com/user-attachments/assets/6024b023-5476-4538-bb4c-cd5332e010cf)

**Comment by alexxus** [comment]
I've got the same issue. Using Laravel 8.83.27

**Comment by Vectorial1024** [comment]
@cosmincmihai @benjaminhansen @alexxus 

I have created a new package that can efficiently remove expired `file` and `database` cache items in Laravel:

- GitHub https://github.com/Vectorial1024/laravel-cache-evict
- Packagist https://packagist.org/packages/vectorial1024/laravel-cache-evict

Extra care has been taken to ensure the types are correct in the package. For example, in this given case, the package would notice that the file is empty and assume the file expires at Unix time 0, which instantly marks the file as "expired". This allows such empty files to be removed by the package correctly.
