### ISSUE TITLE
Handle missing files during expired cache clearing

### ISSUE THREAD

**Issue by jonhassall** [arifhp86/laravel-clear-expired-cache-file#9]
I've noticed that in environments with highly active file caches, the clearing command can sometimes fail with a 'file not found' error. This seems to happen because files may be deleted between the time they're identified as expired and when the command attempts to process them.

My proposed feature would log a warning but continue processing other expired cache entries. Would you be open to either adding this, or I could create it and submit a pull request?

**Comment by arifhp86** [comment]
Thank you for identifying the issue.
This should be fixed by https://github.com/arifhp86/laravel-clear-expired-cache-file/pull/10

**Comment by jonhassall** [comment]
Worked perfectly. Thank you.
